### ISSUE TITLE
Files not deleted

### ISSUE THREAD

**Issue by alexferrari88** [JesseTG/rm#4]
Hi, I have created a workflow that uses your action.
The action runs successfully.
After your action, I have one to show the content of directory, to check whether the file has been actually removed.
After the workflow is complete, though, I can still see the file in GitHub!
Any idea?

This is my action:

```
name: "Delete blockers"

on:
  repository_dispatch:
    types: [delete-blockers]

jobs:
  delete-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
                  
      - name: Remove File
        uses: JesseTG/rm@v1.0.2
        with:
          path: todelete.txt
      
        
      - name: Content current directory
        run: ls
```
